// AUTO-GENERATED by backend/generate_illustrations.py - do not edit by hand.
// scene id -> the variant letters that exist on disk for it.
export const ILLUSTRATION_VARIANTS: Record<string, string[]> = {
  "ant-01": [
    "a"
  ],
  "ant-02": [
    "a"
  ],
  "ant-03": [
    "a"
  ],
  "ant-04": [
    "a"
  ],
  "ant-05": [
    "a"
  ],
  "ant-06": [
    "a"
  ],
  "ant-07": [
    "a"
  ],
  "ant-08": [
    "a"
  ],
  "ant-09": [
    "a"
  ],
  "ant-10": [
    "a"
  ],
  "bee-01": [
    "a"
  ],
  "bee-02": [
    "a"
  ],
  "bee-03": [
    "a"
  ],
  "bee-04": [
    "a"
  ],
  "bee-05": [
    "a"
  ],
  "bee-06": [
    "a"
  ],
  "bee-07": [
    "a"
  ],
  "bee-08": [
    "a"
  ],
  "bee-09": [
    "a"
  ],
  "bee-10": [
    "a"
  ],
  "calf-01": [
    "a"
  ],
  "calf-02": [
    "a"
  ],
  "calf-03": [
    "a"
  ],
  "calf-04": [
    "a"
  ],
  "calf-05": [
    "a"
  ],
  "calf-06": [
    "a"
  ],
  "calf-07": [
    "a"
  ],
  "calf-08": [
    "a"
  ],
  "calf-09": [
    "a"
  ],
  "calf-10": [
    "a"
  ],
  "camel-01": [
    "a"
  ],
  "camel-02": [
    "a"
  ],
  "camel-03": [
    "a"
  ],
  "camel-04": [
    "a"
  ],
  "camel-05": [
    "a"
  ],
  "camel-06": [
    "a"
  ],
  "camel-07": [
    "a"
  ],
  "camel-08": [
    "a"
  ],
  "camel-09": [
    "a"
  ],
  "camel-10": [
    "a"
  ],
  "cave-dog-01": [
    "a"
  ],
  "cave-dog-02": [
    "a"
  ],
  "cave-dog-03": [
    "a"
  ],
  "cave-dog-04": [
    "a"
  ],
  "cave-dog-05": [
    "a"
  ],
  "cave-dog-06": [
    "a"
  ],
  "cave-dog-07": [
    "a"
  ],
  "cave-dog-08": [
    "a"
  ],
  "cave-dog-09": [
    "a"
  ],
  "cave-dog-10": [
    "a"
  ],
  "cave-spider-01": [
    "a"
  ],
  "cave-spider-02": [
    "a"
  ],
  "cave-spider-03": [
    "a"
  ],
  "cave-spider-04": [
    "a"
  ],
  "cave-spider-05": [
    "a"
  ],
  "cave-spider-06": [
    "a"
  ],
  "cave-spider-07": [
    "a"
  ],
  "cave-spider-08": [
    "a"
  ],
  "cave-spider-09": [
    "a"
  ],
  "cave-spider-10": [
    "a"
  ],
  "cow-01": [
    "a"
  ],
  "cow-02": [
    "a"
  ],
  "cow-03": [
    "a"
  ],
  "cow-04": [
    "a"
  ],
  "cow-05": [
    "a"
  ],
  "cow-06": [
    "a"
  ],
  "cow-07": [
    "a"
  ],
  "cow-08": [
    "a"
  ],
  "cow-09": [
    "a"
  ],
  "cow-10": [
    "a"
  ],
  "donkey-01": [
    "a"
  ],
  "donkey-02": [
    "a"
  ],
  "donkey-03": [
    "a"
  ],
  "donkey-04": [
    "a"
  ],
  "donkey-05": [
    "a"
  ],
  "donkey-06": [
    "a"
  ],
  "donkey-07": [
    "a"
  ],
  "elephant-01": [
    "a"
  ],
  "elephant-02": [
    "a"
  ],
  "elephant-03": [
    "a"
  ],
  "elephant-04": [
    "a"
  ],
  "elephant-05": [
    "a"
  ],
  "elephant-06": [
    "a"
  ],
  "elephant-07": [
    "a"
  ],
  "elephant-08": [
    "a"
  ],
  "elephant-09": [
    "a"
  ],
  "elephant-10": [
    "a"
  ],
  "fish-01": [
    "a"
  ],
  "fish-02": [
    "a"
  ],
  "fish-03": [
    "a"
  ],
  "fish-04": [
    "a"
  ],
  "fish-05": [
    "a"
  ],
  "fish-06": [
    "a"
  ],
  "fish-07": [
    "a"
  ],
  "fish-08": [
    "a"
  ],
  "fish-09": [
    "a"
  ],
  "fish-10": [
    "a"
  ],
  "hoopoe-01": [
    "a"
  ],
  "hoopoe-02": [
    "a"
  ],
  "hoopoe-03": [
    "a"
  ],
  "hoopoe-04": [
    "a"
  ],
  "hoopoe-05": [
    "a"
  ],
  "hoopoe-06": [
    "a"
  ],
  "hoopoe-07": [
    "a"
  ],
  "hoopoe-08": [
    "a"
  ],
  "hoopoe-09": [
    "a"
  ],
  "hoopoe-10": [
    "a"
  ],
  "raven-01": [
    "a"
  ],
  "raven-02": [
    "a"
  ],
  "raven-03": [
    "a"
  ],
  "raven-04": [
    "a"
  ],
  "raven-05": [
    "a"
  ],
  "raven-06": [
    "a"
  ],
  "raven-07": [
    "a"
  ],
  "raven-08": [
    "a"
  ],
  "raven-09": [
    "a"
  ],
  "raven-10": [
    "a"
  ]
};
